kind: pipline
name: default
type: kubernetes
node_selector:
  drone: true

steps:
- name: greeting
  image: alpine:3.12.0
  commands:
  - echo hello
  - echo world
  when:
    branch:
    - master
    event:
    - push
