kind: pipeline
name: default
type: kubernetes
node_selector:
  drone: true

steps:
- name: loevdal
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hakloev/loevdal
    auto_tag: true
    cache_from:
      - hakloev/loevdal:latest
  when:
    branch:
    - master
    event:
    - push
  volumes:
    - name: docker-socker
      host:
        path: /var/run/docker.sock:/var/run/docker.sock
