version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: 'Static.Dockerfile'
        depends_on:
            - django
        ports:
            - '80:80'
    django:
        build:
            context: .
            dockerfile: 'Django.Dockerfile'
        env_file:
          - .env
        expose:
            - 8080
